# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: SolusVMNAT
release: 
  github:
     owner: CoiaPrant
     name: SolusVMNAT
before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod download
    # you may remove this if you don't need go generate
   # - go generate ./...
builds:
-
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
      - mips64le
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
